#!/usr/bin/env bash

set -euo pipefail

DOCKER=${DOCKER:-"docker"}
DOCKER_FLAGS=${DOCKER_FLAGS:-""}

RUGIX_DEV=${RUGIX_DEV:-"false"}

RUGIX_CACHE_VOLUME=${RUGIX_CACHE_VOLUME:-"rugix-build-cache"}

if [ "${RUGIX_DEV}" = "false" ]; then
    DOCKER_FLAGS="${DOCKER_FLAGS} --pull always"
    RUGIX_VERSION=${RUGIX_VERSION:-"v0.8"}
else
    RUGIX_VERSION=${RUGIX_VERSION:-"dev"}
fi

RUGIX_BAKERY_IMAGE=${RUGIX_BAKERY_IMAGE:-"ghcr.io/silitics/rugix-bakery:${RUGIX_VERSION}"}

if [ -t 0 ] && [ -t 1 ]; then
    DOCKER_FLAGS="${DOCKER_FLAGS} -it"
fi

if [ -n "${RUGIX_CACHE_VOLUME}" ]; then
    $DOCKER volume create "${RUGIX_CACHE_VOLUME}"
    DOCKER_FLAGS="${DOCKER_FLAGS} -v ${RUGIX_CACHE_VOLUME}:/var/rugix-bakery/cache"
fi

exec $DOCKER run --rm --privileged \
    $DOCKER_FLAGS \
    -v "$(pwd)":/project \
    -v /dev:/dev \
    "${RUGIX_BAKERY_IMAGE}" \
    "$@"
