#!/usr/bin/env bash

set -euo pipefail

DOCKER=${DOCKER:-"docker"}

COMPOSE_FILE="./xtask/devenv/compose.yml"

if [ $($DOCKER compose --file "$COMPOSE_FILE" ps -q | wc -l) -gt 0 ]; then
    echo "Development environment is already running."
else
    echo "Starting development environment."
    $DOCKER compose --file "$COMPOSE_FILE" up --build -d
fi

if [ "${1:-}" = "devenv" ]; then
    shift
    exec $DOCKER compose \
        --file ./xtask/devenv/compose.yml \
        "$@"
fi

if [ "${1:-}" = "shell" ]; then
    exec $DOCKER compose \
        --file ./xtask/devenv/compose.yml \
        exec --privileged devenv "/project/xtask/devenv/run.sh" zsh
fi

exec $DOCKER compose \
    --file ./xtask/devenv/compose.yml \
    exec --privileged devenv "/project/xtask/devenv/run.sh" cargo xtask "$@"
