FROM debian:bookworm

RUN apt-get update -y \
    && apt-get install -y mmdebstrap \
    && apt-get -y clean \
    && rm -rf /var/lib/apt/lists/*

ARG SOURCE_DATE_EPOCH
ENV SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH}

ARG DEBIAN_SNAPSHOT
ENV DEBIAN_SNAPSHOT=${DEBIAN_SNAPSHOT}

ARG DEBIAN_SUITE
ENV DEBIAN_SUITE=${DEBIAN_SUITE}

WORKDIR /build
COPY scripts .
