import React from "react"
import clsx from "clsx"
import Link from "@docusaurus/Link"
import useDocusaurusContext from "@docusaurus/useDocusaurusContext"
import Layout from "@theme/Layout"
import HomepageFeatures from "@site/src/components/HomepageFeatures"
import Admonition from "@theme/Admonition"

import DebianLogo from "@site/static/img/logos/debian.svg"
import AlpineLinuxLogo from "@site/static/img/logos/alpine-linux.svg"

import styles from "./index.module.css"

const SupportedDistributions: React.FC<{}> = () => {
  return (
    <>
      <h3 className="text-center">Supported Distributions</h3>
      <p className="text-center">
        Rugpi supports building images based on{" "}
        <a href="https://www.debian.org/" target="_blank">
          Debian
        </a>
        ,{" "}
        <a href="https://alpinelinux.org/" target="_blank">
          Alpine Linux
        </a>
        , and{" "}
        <a href="https://www.raspberrypi.com/software/" target="_blank">
          Raspberry Pi OS
        </a>
        .
      </p>
      <div className="rounded-xl mb-4 mx-auto py-5 px-10 w-fit bg-gray-200">
        <div className="flex flex-wrap space-x-10 justify-center items-center">
          <a href="https://www.debian.org/" target="_blank" className="h-20">
            <DebianLogo className="h-full w-fit" />
          </a>
          <a
            href="https://alpinelinux.org/"
            target="_blank"
            className="flex items-center h-20"
          >
            <AlpineLinuxLogo viewBox="0 0 665 162" className="h-12 w-fit" />
          </a>
          <a
            href="https://www.raspberrypi.com/"
            target="_blank"
            className="h-20"
          >
            <img
              src={require("@site/static/img/logos/raspios.png").default}
              className="h-full"
            />
          </a>
        </div>
      </div>
      <p className="text-center">
        It can also be used with root filesystems generated by other tools,
        e.g.,{" "}
        <a href="https://www.yoctoproject.org/" target="_blank">
          Yocto Project
        </a>{" "}
        or{" "}
        <a href="https://buildroot.org/" target="_blank">
          Buildroot
        </a>
        .
      </p>
    </>
  )
}

function HomepageHeader() {
  return (
    <header
      className={clsx("hero hero--primary", styles.heroBanner, styles.hero)}
    >
      <div className="container">
        <h1 className="hero__title">
          Robust Building Blocks for Linux-based Devices
        </h1>
        <p className="hero__subtitle">
          Rugpi is an open-source platform empowering you to build innovative
          devices around customized Linux distributions.
        </p>
        <p style={{ maxWidth: "80ch", margin: "1.5em auto" }}>
          Rugpi enables you to{" "}
          <strong>
            build commercial-grade, customized variants of popular Linux
            distributions{" "}
          </strong>
          for your devices. It boasts three core features designed to work
          seamlessly together: (1) A modern, flexible workflow to build
          customized system images, (2) robust{" "}
          <strong>over-the-air system updates with rollback support</strong> for
          the entire system, and (3) <strong>managed state</strong> that is
          preserved across reboots and updates.
        </p>
        <div className={styles.buttons}>
          <Link
            className="button button--secondary button--lg"
            to="/docs/getting-started"
          >
            Get Started 🚀
          </Link>
        </div>
      </div>
    </header>
  )
}

export default function Home(): JSX.Element {
  const { siteConfig } = useDocusaurusContext()
  return (
    <Layout title="Home" description={siteConfig.tagline}>
      <HomepageHeader />
      <main>
        <div style={{ maxWidth: "80ch", padding: "3rem 0", margin: "0 auto" }}>
          <Admonition type="info" title="Stability Guarantees">
            <p>
              While Rugpi is a young and evolving project, we understand that
              device lifetimes typically span multiple years, if not decades. We
              are committed to maintain backwards-compatibility for updates.
              This ensures that devices using Rugpi can be updated in the
              future. If you're developing anything with Rugpi, please be aware
              that the building pipeline, CLI, and APIs may still change.
            </p>
          </Admonition>
        </div>
        <SupportedDistributions />
        <HomepageFeatures />
      </main>
    </Layout>
  )
}
