#!/usr/bin/env bash

set -euo pipefail

DOCKER=${DOCKER:-"docker"}
DOCKER_FLAGS=${DOCKER_FLAGS:-""}

RUGIX_DEV=${RUGIX_DEV:-"false"}

if [ "${RUGIX_DEV}" = "false" ]; then
    DOCKER_FLAGS="${DOCKER_FLAGS} --pull always"
    RUGIX_VERSION=${RUGIX_VERSION:-"%%DEFAULT_VERSION%%"}
else
    RUGIX_VERSION=${RUGIX_VERSION:-"dev"}
fi

RUGIX_BAKERY_IMAGE=${RUGIX_BAKERY_IMAGE:-"ghcr.io/silitics/rugix-bakery:${RUGIX_VERSION}"}

if [ -t 0 ] && [ -t 1 ]; then
    DOCKER_FLAGS="${DOCKER_FLAGS} -it"
fi

exec $DOCKER run --rm --privileged \
    $DOCKER_FLAGS \
    -v "$(pwd)":/project \
    -v /dev:/dev \
    "${RUGIX_BAKERY_IMAGE}" \
    "$@"
